### ISSUE TITLE
I wonder why we use conv3d

### ISSUE THREAD

**Issue by nobile98** [syamkakarla98/Satellite_Imagery_Analysis#1]
Hi!! I have a question about conv3d
Normally the image uses conv2d, but here we have confirmed that conv3d is used. I'm curious why you use conv3d.

thanks.

**Comment by syamkakarla98** [comment]
Generally, 2D CNN is used to extract spectral features but using 3D CNN followed by a 2D CNN will provide spectral-spatial feature extraction as the satellite imagery is multispectral.

You can refer to these research papers for a better understanding of the concepts behind using a 3D-2D CNN.

https://ieeexplore.ieee.org/abstract/document/8297014

https://ieeexplore.ieee.org/abstract/document/8736016
